# Generated by Django 5.2.6 on 2025-09-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='last_recovery_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
